podSpec:
  nodeSelector:
    kubernetes.io/os: windows
    kubernetes.io/arch: amd64
  containers: []
  restartPolicy: Never
  serviceAccountName: sonobuoy-serviceaccount
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  - key: CriticalAddonsOnly
    operator: Exists
  - key: kubernetes.io/e2e-evict-taint-key
    operator: Exists
sonobuoy-config:
  driver: Job
  plugin-name: windows-events
  result-format: raw
  skip-cleanup: true
  source_url: https://raw.githubusercontent.com/vmware-tanzu/sonobuoy-plugins/main/examples/windows-plugin/plugin.yaml
  description: Example of a plugin which runs on Windows nodes. Gathers Windows events.
spec:
  image: sonobuoy/windows-plugin:v1
  name: plugin
  resources: {}
  volumeMounts:
  - mountPath: /tmp/results
    name: results

