podSpec:
  containers: []
  nodeSelector:
    kubernetes.io/os: linux
  restartPolicy: Never
  serviceAccountName: sonobuoy-serviceaccount
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  - key: CriticalAddonsOnly
    operator: Exists
  - key: kubernetes.io/e2e-evict-taint-key
    operator: Exists
sonobuoy-config:
  driver: Job
  plugin-name: custom-e2e
  result-format: raw
spec:
  command:
  - bash
  args: ["-c","go tool test2json ./custom.test -test.v > /tmp/results/out.json && echo '/tmp/results/out.json' > /tmp/results/done"]
  image: schnake/custome2e:v1
  name: plugin
  resources: {}
  volumeMounts:
  - mountPath: /tmp/results
    name: results

