sonobuoy-config:
  driver: Job
  plugin-name: custom-e2e
  result-format: gojson
spec:
  command:
  - bash
  args: ["-c","go tool test2json ./custom.test -test.v | tee ${SONOBUOY_RESULTS_DIR}/out.json ; echo ${SONOBUOY_RESULTS_DIR}/out.json > ${SONOBUOY_RESULTS_DIR}/done"]
  image: schnake/custome2e:v0.2.0
  env:
  - name: NS_PREFIX
    value: custom
  - name: SONOBUOY_PROGRESS_PORT
    value: "8099"
  name: plugin
  resources: {}
  volumeMounts:
  - mountPath: /tmp/sonobuoy/results
    name: results

